### ISSUE TITLE
Error publishing while sending sensor values

### ISSUE THREAD

**Issue by mklewandowski** [manylabs/sensaurus#1]
We occasionally see the following error message in the serial logger when the ESP32 hub attempts to publish the `sensors` MQTT message containing real-time sensor values:
`sending values: error publishing`
This error message appears more frequently when 1 of 2 things also happens: 
* when 1 or more checksum errors occur while reading sensor values
* when the hub receives a `command` MQTT message (so we will see the hub process the `command` message and then shortly after we will see `sending values: error publishing` in the serial logger).

**Comment by petermichalek** [comment]
This is now resolved, Matt can you please confirmed it works for you and close it?

**Comment by mklewandowski** [comment]
Peter, to confirm we do NOT need to update the devices to test this issue, correct?  If true, I will be able to test later today and close the issue.  Thanks!

**Comment by petermichalek** [comment]
It may work without an update to devices, there have been some optimization added in the last week such as BUFFERING (currently enabled) and DELAY (currently disabled by default) ifdefs, but I didn't see them affect behavior much.
Generally it's always best to use the latest firmware on devices as well to make sure we are testing under identical circumstances.

**Comment by mklewandowski** [comment]
I'm no longer seeing the error publishing messages.  Closing this.
